### ISSUE TITLE
Link control is not working as expected in Pega Web Mashup component

### ISSUE THREAD

**Issue by MaheshSunkara** [pegasystems/mashup-webcomponent#2]
When trying to launch a local action(in Modal Dialog) on click of a link in Pega Mashup via action set, this is not working as expected. Case is getting refreshed but the local action is not opening. Not only this, Link control is not working as expected when i tried to do refresh this section aswell. Could you please provide us fix for this issue?

**Comment by ricmars** [comment]
I have improved the codebase to add support for local action for the dx api v1 - you can get more details here https://github.com/pegasystems/mashup-webcomponent/wiki/List-of-changes - please use this issue to provide feedback if the new functionality is addressing your needs. Note that the local action should be used with a button, not a link.

I have updated the demo case type to show this use case.
![image](https://user-images.githubusercontent.com/29442140/117145130-c821a780-ad80-11eb-8c3a-1e32a0735cd0.png)

**Comment by MaheshSunkara** [comment]
Hi Richard, thanks for implementing this functionality in GitHub component. But our requirement is to launch the local action from a link but you have mentioned to use a button. Is the limitation of link control in DX API or yet to be implemented in GitHub component? please let us know.

**Comment by ricmars** [comment]
Links should be used to navigate to a NEW page - A button is used to fire any action when a user interacts with it, including submitting Forms. Unlike Links, they do not perform navigation. see https://design.pega.com/components/button/

Links should have a valid href defined so that the link can be opened in a new browser tab using right-click. While in Pega you can put action like 'run local action' on any component, there are some best practices that you should follow for accessibility and semantic markup reasons. 

If the reason to use a link is that you want it to look like a link, then you should use the 'Simple' button format. The mashup component will work with a link but will always generate the markup as a button. I have updated the sample app and changed the format from Standard' to Simple.

Can you please confirm that the new functionality is addressing your needs so that I can close this enhancement request. Thanks

**Comment by MaheshSunkara** [comment]
Hi Richard,
This will serve our purpose. But, I tried the same logic from my end by adding optional action in the stage in case type. And added button and configured it with action(run local action) and event(click). It is not working as expected. Can you please see if everything is committed from your end?

**Comment by ricmars** [comment]
yes the code is checked in - are you running it locally or from the github page? What console error and network error are you getting?

**Comment by MaheshSunkara** [comment]
Nothing is happening on click of this button. We have seen no entries in the console and network trace although we have added the actions set on the button.

**Comment by ricmars** [comment]
please schedule a meeting with me to review the issue and better understand how you plan to use the web component. my email is richard.marsot@pega.com. Thanks

**Comment by MaheshSunkara** [comment]
Can we connect 4.30PM CET today? If ok, I will share the meeting details with you on your email id.

**Comment by ricmars** [comment]
yes looks good - please send invite with connection details

**Comment by MaheshSunkara** [comment]
Hi Richard, I have invited you to the meeting today at 4.30PM CET. Please check your email, incase you didn't receive the invite please let us know so that we will post the invite here.

**Comment by ricmars** [comment]
demo example works fine in 8.5 and 8.4 - Mahesh was having an issue during submit where the current assignment view was not rendered after submit.
